---

- name: Determine if EPEL repo is already present
  stat:
    path: "{{ epel_repo_file }}"
  register: epel_repo_file_status

- name: RHEL OS Version Specific Tasks
  include_tasks: "rhel{{ ansible_distribution_major_version }}.yml"

- name: Add EPEL Repo
  yum:
    name: "{{ epel_repo_url }}"
    state: "present"
    disable_gpg_check: "true"
  when: epel_repo_file_status.stat.exists == False
